### ISSUE TITLE
Addon is hiding some action bar keybinds

### ISSUE THREAD

**Issue by parsimonious** [SweepyBoop/Sweepy-Boop#228]
After the update 2 hours ago, I've noticed that my action bar keybinds are being hidden by Sweepy-Boop's. It's inconsistent, sometimes all of them sometimes none of them. This behavior happens when I have sweepy-Boop's installed alongside no other addons and go aways when I disable this. Any idea what might have changed?

**Comment by SweepyBoop** [comment]
I think I accidentally included some change that is only for myself locally.
It should be fixed now.
Could you check?

**Comment by parsimonious** [comment]
Looks fixed to me! Thanks for taking care of that, still love the addon.
