### ISSUE TITLE
11 Lua Error

### ISSUE THREAD

**Issue by carlos5152** [SweepyBoop/Sweepy-Boop#229]
Hi the addon is not working with the following Lua error :

17x SweepyBoop/Core.lua:2: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@SweepyBoop/Core.lua"]:2: in main chunk

Locals:
addonName = "SweepyBoop"
NS = <table> {
 NAME_PLATE_UNIT_REMOVED = "NAME_PLATE_UNIT_REMOVED"
 SPECID = <table> {
 }
 spellResets = <table> {
 }
 SPELL_SUMMON = "SPELL_SUMMON"
 MAGE = "MAGE"
 UNIT_MAXPOWER = "UNIT_MAXPOWER"
 cooldownSpells = <table> {
 }
 DEFAULT_ICON_SIZE = 32
 ARENA_PREP_OPPONENT_SPECIALIZATIONS = "ARENA_PREP_OPPONENT_SPECIALIZATIONS"
 isTestMode = false
 UNIT_MAXHEALTH = "UNIT_MAXHEALTH"
 MONK = "MONK"
 UNIT_POWER_FREQUENT = "UNIT_POWER_FREQUENT"
 UPDATE_SHAPESHIFT_FORM = "UPDATE_SHAPESHIFT_FORM"
 UNIT_SPELLCAST_SUCCEEDED = "UNIT_SPELLCAST_SUCCEEDED"
 PLAYER_SPECIALIZATION_CHANGED = "PLAYER_SPECIALIZATION_CHANGED"
 SPELL_EMPOWER_END = "SPELL_EMPOWER_END"
 PARTY_KILL = "PARTY_KILL"
 UNIT_HEALTH = "UNIT_HEALTH"
 WARLOCK = "WARLOCK"
 DEMONHUNTER = "DEMONHUNTER"
 SPELL_AURA_APPLIED = "SPELL_AURA_APPLIED"
 PLAYER_TARGET_CHANGED = "PLAYER_TARGET_CHANGED"
 SPELL_DISPEL = "SPELL_DISPEL"
 SPELL_AURA_REMOVED = "SPELL_AURA_REMOVED"
 SPELL_CAST_START = "SPELL_CAST_START"
 RESET_FULL = 0
 LOSS_OF_CONTROL_UPDATE = "LOSS_OF_CONTROL_UPDATE"
 HIDETIMEROMNICC = "BoopHideTimer"
 BAG_UPDATE = "BAG_UPDATE"
 WARRIOR = "WARRIOR"
 SHAMAN = "SHAMAN"
 GROUP_ROSTER_UPDATE = "GROUP_ROSTER_UPDATE"
 ROGUE = "ROGUE"
 SPELL_DAMAGE = "SPELL_DAMAGE"
 PLAYER_REGEN_ENABLED = "PLAYER_REGEN_ENABLED"
 PALADIN = "PALADIN"
 HUNTER = "HUNTER"
 UNIT_AURA = "UNIT_AURA"
 EVOKER = "EVOKER"
 DEATHKNIGHT = "DEATHKNIGHT"
 DRUID = "DRUID"
 SPELL_INTERRUPT = "SPELL_INTERRUPT"
 COMBAT_LOG_EVENT_UNFILTERED = "COMBAT_LOG_EVENT_UNFILTERED"
 UNIT_DIED = "UNIT_DIED"
 PLAYER_ENTERING_WORLD = "PLAYER_ENTERING_WORLD"
 DURATION_DYNAMIC = "dynamic"
 PRIEST = "PRIEST"
 spellData = <table> {
 }
 UNIT_TARGET = "UNIT_TARGET"
 SPELLCATEGORY = <table> {
 }
 cooldownResets = <table> {
 }
 LOSS_OF_CONTROL_ADDED = "LOSS_OF_CONTROL_ADDED"
 SPELL_CAST_SUCCESS = "SPELL_CAST_SUCCESS"
 NAME_PLATE_UNIT_ADDED = "NAME_PLATE_UNIT_ADDED"
 UNIT_PET = "UNIT_PET"
}
(*temporary) = nil
(*temporary) = "SweepyBoop"
(*temporary) = "Title"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"

**Comment by SweepyBoop** [comment]
Should be resolved with the latest update
