### ISSUE TITLE
[Feature Request] Show class icons on enemies

### ISSUE THREAD

**Issue by RealJig** [SweepyBoop/Sweepy-Boop#232]
I would like to see the icons on the enemy players as well

**Comment by sevenuncler** [comment]
plus+

**Comment by SweepyBoop** [comment]
Recent updates added arena enemy spec icon, you can show healer only or show all.
Reason I'm not adding class icon for enemies is it's duplicate information with nameplate coloring, and it confuses players with friendly class icons.
